import { useState, useEffect } from 'react';
import { TopAnnouncement } from './components/layout/TopAnnouncement';
import { Navbar } from './components/layout/Navbar';
import { Footer } from './components/layout/Footer';
import { HeroSection } from './components/hero/HeroSection';
import { AllInOneGrid } from './components/features/AllInOneGrid';
import { TeachingTracksSection } from './components/tracks/TeachingTracksSection';
import { CommunityDevelopersSection } from './components/community/CommunityDevelopersSection';
import { CommunityHubSection } from './components/community/CommunityHubSection';
import { FeatureDeepDives } from './components/features/FeatureDeepDives';
import { PricingSection } from './components/pricing/PricingSection';
import { TestimonialsSection } from './components/social-proof/TestimonialsSection';
import { FAQSection } from './components/faq/FAQSection';
import { FinalCTA } from './components/cta/FinalCTA';
import { AuthModal } from './components/modals/AuthModal';
import { TrackDetailModal } from './components/modals/TrackDetailModal';
import { CourseBuilderModal } from './components/studio/CourseBuilderModal';
import { TeacherSetupModal } from './components/teachers/TeacherSetupModal';
import { CheckoutModal } from './components/modals/CheckoutModal';
import { DeveloperProfileModal } from './components/modals/DeveloperProfileModal';
import { ApplyTenantModal } from './components/modals/ApplyTenantModal';
import { getCurrentUser, supabase } from './lib/supabaseClient';
import type { Track, CommunityDeveloper } from './types';
import { CreateCommunityModal } from './components/modals/CreateCommunityModal';
import { CommunityFeed } from './components/community/CommunityFeed';

// =========================================================================
// COC 1: INSTALLING AND CONFIGURING COMPUTER SYSTEMS (14 Lessons)
// =========================================================================
const COC1_LESSONS = [
  { id: 1, title: 'Introduction to Computer Systems', duration: '4 Hours', objective: 'Understand the fundamental architecture of modern computer systems and data processing cycle.', content: 'Covers input, processing, output, and storage devices. Explores von Neumann architecture.', videoUrl: 'https://www.youtube.com/embed/kUMe1FH4CHE', activity: 'Create a system block diagram classifying peripherals.', quiz: 'Identify the primary function of the ALU.', classroomLink: '', progress: 100 },
  { id: 2, title: 'Computer Hardware Components', duration: '6 Hours', objective: 'Identify and inspect internal and external hardware components including CPU, RAM, and motherboards.', content: 'Detailed study of CPU sockets, motherboard form factors, RAM types, and storage drives.', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', activity: 'List motherboard specifications and compatibility check.', quiz: 'What is the difference between volatile and non-volatile memory?', classroomLink: '', progress: 0 },
  { id: 3, title: 'Occupational Health and Safety (OHS)', duration: '4 Hours', objective: 'Apply OHS policies and procedures in computer laboratory environments, including ESD protection.', content: 'Proper grounding techniques, anti-static wrist straps, mat usage, and emergency protocols.', videoUrl: 'https://www.youtube.com/embed/3Q9X7vFjXU4', activity: 'Draft an OHS safety checklist for an IT workstation setup.', quiz: 'Why is an anti-static wrist strap critical when assembling a PC?', classroomLink: '', progress: 0 },
  { id: 4, title: 'Computer Assembly and Disassembly', duration: '10 Hours', objective: 'Safely assemble and disassemble a complete desktop computer system.', content: 'Motherboard mounting, CPU installation, thermal paste application, heatsink mounting, PSU wiring.', videoUrl: 'https://www.youtube.com/embed/hQic7h6XqKA', activity: 'Perform physical assembly and cable management on a training PC rig.', quiz: 'What is the correct pin orientation for power switch headers?', classroomLink: '', progress: 0 },
  { id: 5, title: 'BIOS/UEFI Configuration', duration: '6 Hours', objective: 'Navigate and configure BIOS/UEFI firmware settings and boot priorities.', content: 'Accessing BIOS via hotkeys, configuring boot order for USB media, and enabling virtualization.', videoUrl: 'https://www.youtube.com/embed/W5kCg2dfnFk', activity: 'Configure boot sequence and secure boot options in BIOS.', quiz: 'How do you reset a forgotten BIOS password?', classroomLink: '', progress: 0 },
  { id: 6, title: 'Operating System Installation', duration: '10 Hours', objective: 'Install modern operating systems from bootable USB media.', content: 'Creating bootable media using Rufus, partition formatting (GPT vs MBR), and clean OS installation.', videoUrl: 'https://www.youtube.com/embed/5mY7y_x4ZlQ', activity: 'Execute a clean installation of Windows 11 on a formatted partition.', quiz: 'What partition style is required for UEFI boot with drives over 2TB?', classroomLink: '', progress: 0 },
  { id: 7, title: 'Device Drivers Installation', duration: '6 Hours', objective: 'Install and update hardware device drivers for optimal performance.', content: 'Using Device Manager to identify missing drivers and installing chipset, graphics, and network drivers.', videoUrl: 'https://www.youtube.com/embed/kUMe1FH4CHE', activity: 'Verify all hardware drivers are installed without warning icons.', quiz: 'Where can you check if a driver failed to load?', classroomLink: '', progress: 0 },
  { id: 8, title: 'Application Software Installation', duration: '6 Hours', objective: 'Install and configure productivity suites, antivirus, and utility applications.', content: 'Installing Microsoft Office / LibreOffice, antivirus packages, PDF readers, and archiving tools.', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', activity: 'Install standard productivity tools and verify activation.', quiz: 'What is the purpose of installing anti-malware software?', classroomLink: '', progress: 0 },
  { id: 9, title: 'Computer Configuration', duration: '6 Hours', objective: 'Configure operating system settings, user accounts, and power options.', content: 'Setting up local user accounts, configuring Windows Update, and screen resolution.', videoUrl: 'https://www.youtube.com/embed/3Q9X7vFjXU4', activity: 'Create custom user accounts and adjust power profiles.', quiz: 'What privilege level is required to install system software?', classroomLink: '', progress: 0 },
  { id: 10, title: 'Network Configuration Basics', duration: '6 Hours', objective: 'Configure TCP/IPv4 network settings, static IP addressing, and connectivity.', content: 'Understanding IP addresses, subnet masks, default gateways, and ping command testing.', videoUrl: 'https://www.youtube.com/embed/hQic7h6XqKA', activity: 'Assign a static IP address and test connectivity.', quiz: 'What command-line tool tests network reachability?', classroomLink: '', progress: 0 },
  { id: 11, title: 'Testing and Troubleshooting', duration: '8 Hours', objective: 'Diagnose and resolve common hardware and software faults.', content: 'POST beep code analysis, blue screen troubleshooting, and RAM testing.', videoUrl: 'https://www.youtube.com/embed/W5kCg2dfnFk', activity: 'Simulate and resolve a RAM seating error scenario.', quiz: 'What do continuous short beeps during POST indicate?', classroomLink: '', progress: 0 },
  { id: 12, title: 'Preventive Maintenance', duration: '4 Hours', objective: 'Perform scheduled preventive maintenance to extend hardware lifespan.', content: 'Dust cleaning using compressed air, disk cleanup, and defragmentation.', videoUrl: 'https://www.youtube.com/embed/5mY7y_x4ZlQ', activity: 'Execute a digital disk cleanup and defragmentation routine.', quiz: 'How often should physical dust cleaning be performed?', classroomLink: '', progress: 0 },
  { id: 13, title: 'Documentation and Work Completion', duration: '4 Hours', objective: 'Complete service reports, inventory logs, and customer turnover documentation.', content: 'Recording serial numbers, software licenses, maintenance logs, and customer sign-off.', videoUrl: 'https://www.youtube.com/embed/kUMe1FH4CHE', activity: 'Fill out a standard IT Technical Service Report Form.', quiz: 'Why is maintaining an accurate hardware inventory log important?', classroomLink: '', progress: 0 },
  { id: 14, title: 'COC 1 Practical Assessment', duration: '10 Hours', objective: 'Demonstrate complete mastery of COC 1 through timed practical performance tasks.', content: 'Comprehensive performance evaluation covering assembly, BIOS, OS installation, and troubleshooting.', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', activity: 'Complete the timed practical demonstration rubric.', quiz: 'Submit final performance checklist and practical competency log.', classroomLink: '', progress: 0 }
];

// =========================================================================
// COC 2: SET UP COMPUTER NETWORKS (12 Lessons)
// =========================================================================
const COC2_LESSONS = [
  { id: 1, title: 'Introduction to Computer Networking', duration: '4 Hours', objective: 'Understand network fundamentals including LAN, WAN, WLAN, topologies, and devices.', content: 'What is a computer network? LAN vs WAN vs WLAN, topologies, and basic network devices.', videoUrl: 'https://www.youtube.com/embed/3Q9X7vFjXU4', activity: 'Draw a network topology diagram for a small office network.', quiz: 'What topology uses a central switch or hub connecting all nodes?', classroomLink: '', progress: 0 },
  { id: 2, title: 'Network Components and Tools', duration: '6 Hours', objective: 'Identify network media, hardware components, crimping tools, and LAN testers.', content: 'NIC, switches, routers, access points, modems, UTP/STP cables, RJ45 connectors, crimping tools, LAN testers.', videoUrl: 'https://www.youtube.com/embed/hQic7h6XqKA', activity: 'Inspect and catalog network tools and cable connectors.', quiz: 'What tool is used to test continuity on an RJ45 UTP cable?', classroomLink: '', progress: 0 },
  { id: 3, title: 'Network Cabling (T568A / T568B)', duration: '8 Hours', objective: 'Make, terminate, and test straight-through and crossover UTP cables.', content: 'UTP cable color standards T568A and T568B, straight-through vs crossover cables, cable termination.', videoUrl: 'https://www.youtube.com/embed/W5kCg2dfnFk', activity: 'Fabricate and test both a straight-through and crossover UTP cable.', quiz: 'Which standard puts Orange-White on pin 1 for T568B?', classroomLink: '', progress: 0 },
  { id: 4, title: 'IP Addressing (IPv4, Static, DHCP, Subnetting)', duration: '8 Hours', objective: 'Master IPv4 addressing, public vs private IPs, static assignment, DHCP, and subnet masks.', content: 'IPv4 structure, public/private IP ranges, static IP, DHCP servers, subnet masks, default gateways, DNS.', videoUrl: 'https://www.youtube.com/embed/5mY7y_x4ZlQ', activity: 'Calculate subnet ranges and assign static IP configurations.', quiz: 'What is the private IP class range starting with 192.168.0.0?', classroomLink: '', progress: 0 },
  { id: 5, title: 'Setting Up a LAN', duration: '8 Hours', objective: 'Connect computers and network hardware to establish a functioning Local Area Network.', content: 'Connecting computers, linking switches/routers, configuring network adapters, assigning IP addresses.', videoUrl: 'https://www.youtube.com/embed/kUMe1FH4CHE', activity: 'Build a small physical LAN and verify node-to-node connectivity.', quiz: 'What command verifies basic IP layer reachability between two PCs?', classroomLink: '', progress: 0 },
  { id: 6, title: 'Wireless Network Setup', duration: '6 Hours', objective: 'Configure Wi-Fi access points, SSIDs, and enterprise-grade wireless security.', content: 'Wi-Fi configuration, SSID broadcasting, WPA2/WPA3 security protocols, and access point management.', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', activity: 'Configure a wireless router with WPA3 encryption and a custom SSID.', quiz: 'Which wireless security protocol offers the highest standard encryption today?', classroomLink: '', progress: 0 },
  { id: 7, title: 'Network Sharing & Permissions', duration: '6 Hours', objective: 'Set up file, folder, and printer sharing across local network users.', content: 'File/folder sharing, network printer sharing, network discovery, and user security permissions.', videoUrl: 'https://www.youtube.com/embed/3Q9X7vFjXU4', activity: 'Share a network folder and assign read/write permissions to specific users.', quiz: 'What Windows feature must be enabled to see other PCs on the network?', classroomLink: '', progress: 0 },
  { id: 8, title: 'Network Troubleshooting', duration: '8 Hours', objective: 'Diagnose and resolve network connectivity issues using diagnostic CLI tools.', content: 'Using ipconfig, ping, tracert, nslookup. Checking physical cables, switch ports, and IP conflicts.', videoUrl: 'https://www.youtube.com/embed/hQic7h6XqKA', activity: 'Trace packet routing paths and resolve a simulated IP conflict.', quiz: 'What command diagnoses DNS name resolution issues?', classroomLink: '', progress: 0 },
  { id: 9, title: 'Network Security Basics', duration: '6 Hours', objective: 'Implement fundamental network security practices including router hardening and firewalls.', content: 'Strong passwords, router admin security, firewall basics, secure Wi-Fi practices.', videoUrl: 'https://www.youtube.com/embed/W5kCg2dfnFk', activity: 'Change default router administrator credentials and configure basic firewall rules.', quiz: 'Why is changing default router credentials critical for network security?', classroomLink: '', progress: 0 },
  { id: 10, title: 'Network Documentation', duration: '4 Hours', objective: 'Create accurate network diagrams, IP address tables, and cable labeling records.', content: 'Network diagrams, IP address allocation tables, cable labeling standards, and configuration records.', videoUrl: 'https://www.youtube.com/embed/5mY7y_x4ZlQ', activity: 'Draft an IP assignment table and physical cable map for a network lab.', quiz: 'What record tracks all active IP addresses assigned to devices?', classroomLink: '', progress: 0 },
  { id: 11, title: 'Practical Performance Tasks', duration: '10 Hours', objective: 'Execute hands-on networking tasks from cabling and LAN setup to resource sharing.', content: 'Making UTP cables, building a small LAN, static IP setup, DHCP configuration, Wi-Fi setup.', videoUrl: 'https://www.youtube.com/embed/kUMe1FH4CHE', activity: 'Complete the full practical network setup and troubleshooting checklist.', quiz: 'Submit practical performance verification record.', classroomLink: '', progress: 0 },
  { id: 12, title: 'COC 2 Assessment', duration: '6 Hours', objective: 'Pass written examinations, practical tests, and troubleshooting assessments for COC 2.', content: 'Written test, identification, practical lab examination, troubleshooting assessment, and final checklist.', videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', activity: 'Take the comprehensive COC 2 summative evaluation exam.', quiz: 'Complete final competency review items.', classroomLink: '', progress: 0 }
];

// =========================================================================
// COC 3: SET UP COMPUTER SERVERS (13 Lessons)
// =========================================================================
const COC3_LESSONS = [
  { id: 1, title: 'Introduction to Computer Servers', duration: '4 Hours', objective: 'Understand server fundamentals, server vs workstation, and client-server architecture.', content: 'What is a server? Server vs workstation, types of servers, server roles and functions, client-server architecture.', videoUrl: '